apiVersion: apps/v1
kind: Deployment
metadata:
  name: dna-frontend
  namespace: default
  labels:
    app: dna-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dna-frontend
  template:
    metadata:
      labels:
        app: dna-frontend
    spec:
      containers:
        - name: dna-frontend
          image: localhost:32000/dna-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DEPLOY_ENV
              value: "prod"
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: dna-frontend-secrets
