apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dna-frontend
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: dna-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: dna-frontend.instinct.is
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dna-frontend
                port:
                  number: 8080
  tls:
    - hosts:
        - dna-frontend.instinct.is
      secretName: dna-frontend-tls
